config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
  get 'colegios/micolegio'
  resources :docentes
  resources :colegios
  resources :uni_asos
  
  devise_for :usuarios, controllers: {registrations: "registrations"}
  devise_scope :usuario do
    authenticated :usuario do
      root 'welcome#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :usuarios
end

app/models/docente.rb
class Docente < ActiveRecord::Base
  belongs_to :colegio
  before_save :default_values
  cattr_accessor :current_usuario
  
  def default_values
    self.creado_by ||= Docente.current_usuario.usuario
  end
  
end

app/controllers/docentes_controller.rb
class DocentesController < ApplicationController
  before_action :set_docente, only: [:show, :edit, :update, :destroy]

  # GET /docentes
  # GET /docentes.json
  def index
    @docentes = Docente.all
    
    if current_usuario.rol == "Administrador Colegio"
      @docentes = Docente.where("creado_by = ?", current_usuario.usuario)
    end
  end

  # GET /docentes/1
  # GET /docentes/1.json
  def show
  end

  # GET /docentes/new
  def new
    @docente = Docente.new
  end

  # GET /docentes/1/edit
  def edit
  end

  # POST /docentes
  # POST /docentes.json
  def create
    @docente = Docente.new(docente_params)

    respond_to do |format|
      if @docente.save
        format.html { redirect_to @docente, notice: 'Docente was successfully created.' }
        format.json { render :show, status: :created, location: @docente }
      else
        format.html { render :new }
        format.json { render json: @docente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docentes/1
  # PATCH/PUT /docentes/1.json
  def update
    respond_to do |format|
      if @docente.update(docente_params)
        format.html { redirect_to @docente, notice: 'Docente was successfully updated.' }
        format.json { render :show, status: :ok, location: @docente }
      else
        format.html { render :edit }
        format.json { render json: @docente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docentes/1
  # DELETE /docentes/1.json
  def destroy
    @docente.destroy
    respond_to do |format|
      format.html { redirect_to docentes_url, notice: 'Docente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_docente
      @docente = Docente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def docente_params
      params.require(:docente).permit(:cedula, :nombre, :apellido, :telefono, :email, :area, :titulos, :cargo, :colegio_id)
    end
end

app/helpers/docente_helper.rb
module DocenteHelper
end

app/helpers/docentes_helper.rb
module DocentesHelper
end

app/views/docentes/_form.html.erb
<div>
    <div class="col-md-6 center-block no-float form-login padding_top">

<%= form_for(@docente) do |f| %>
  <% if @docente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@docente.errors.count, "error") %> prohibited this docente from being saved:</h2>

      <ul>
      <% @docente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cedula %><br>
    <%= f.text_field :cedula %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :titulos %><br>
    <%= f.text_area :titulos %>
  </div>
  <div class="field">
    <%= f.label :cargo %><br>
    <%= f.text_field :cargo %>
  </div>
  <div class="field">
    <%= f.label :colegio_id %><br>
    <% if current_usuario.rol == "Administrador Colegio"%>
    <%= f.text_field :colegio_id, :value=> current_usuario.nombre %>
    <%else%>
    <%= f.collection_select(:colegio_id, Colegio.all, :nombre, :nombre, :include_blank => "Por favor seleccione...") %>
    <%end%>
  </div>
  <div class="actions">
    <center>
      <a><%= link_to '.', :back, :class=>" fa fa-arrow-circle-o-left fa-2x btn btn-border-info btn-rounded btn-lg" %></a>
      <a><%= f.submit "Ingresar Datos Empleado", :class=>"btn btn-border-info btn-rounded btn-lg" %></a>
    </center>
  </div>
<% end %>
</div>
</div>

<script>
  $(document).ready(function () {
            $('select').material_select();
        });
</script>

app/views/docentes/edit.html.erb
<font face="comic sans ms"><h1 class="text-info">Editar Empleado</h1></font>
<%= render 'form' %>

app/views/docentes/index.html.erb
<font face="comic sans ms"><h1 class="text-info">Empleados</h1></font>

<div class="col-md-10 center-block no-float form-login padding_top">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Telefono</th>
      <th>Cargo</th>
      <th>Colegio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @docentes.each do |docente| %>
      <tr>
        <td><%= docente.nombre %></td>
        <td><%= docente.apellido %></td>
        <td><%= docente.telefono %></td>
        <td><%= docente.cargo %></td>
        <td><%= docente.colegio_id %></td>
        <td><%= link_to '', docente, :class=>"fa fa-eye fa-1x" %></td>
        <td><%= link_to '', edit_docente_path(docente), :class=>"fa fa-pencil fa-1x" %></td>
        <td><%= link_to '', docente, :class=>"fa fa-trash-o fa-1x", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<div class="actions">
  <a><%= link_to 'Nuevo Empleado', new_docente_path, :class=>" fa fa-plus-circle fa-2x btn btn-border-info btn-rounded btn-lg" %></a>
</div>

app/views/docentes/new.html.erb
<font face="comic sans ms"><h1 class="text-info">Nuevo Empleados</h1></font>

<%= render 'form' %>

app/views/docentes/show.html.erb
<div class="col-md-10 center-block no-float form-login padding_top">

<div class="panel panel-info">
  <div class="panel-heading"><center>Uniones y Campos</center></div>
  
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Cedula:</div>
      <div class="col-md-8"><%= @docente.cedula %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Nombre:</div>
      <div class="col-md-8"><%= @docente.nombre %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Apellido:</div>
      <div class="col-md-8"><%= @docente.apellido %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Telefono:</div>
      <div class="col-md-8"><%= @docente.telefono %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Email:</div>
      <div class="col-md-8"><%= @docente.email %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Area:</div>
      <div class="col-md-8"><%= @docente.area %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Tirulos:</div>
      <div class="col-md-8"><%= @docente.titulos %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Cargo:</div>
      <div class="col-md-8"><%= @docente.cargo %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Colegio:</div>
      <div class="col-md-8"><%= @docente.colegio_id %></div>
    </div>
  </div>
</div>

<div class="actions">
  <a><%= link_to 'Back', docentes_path(@user), :class=>" fa fa-arrow-circle-o-left fa-2x btn btn-border-info btn-rounded btn-lg" %></a>
  <a><%= link_to 'Mi Colegio', colegios_micolegio_path, :class=>" fa fa-graduation-cap fa-2x btn btn-border-info btn-rounded btn-lg" %></a>
</div>