config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
  get 'colegios/micolegio'
  resources :docentes
  resources :colegios
  resources :uni_asos
  
  devise_for :usuarios, controllers: {registrations: "registrations"}
  devise_scope :usuario do
    authenticated :usuario do
      root 'welcome#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :usuarios
end

app/models/uni_aso.rb
class UniAso < ActiveRecord::Base
end

app/controllers/uni_asos_controller.rb
class UniAsosController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_uni_aso, only: [:show, :edit, :update, :destroy]

  # GET /uni_asos
  # GET /uni_asos.json
  def index
    @uni_asos = UniAso.all
  end
  
  # GET /uni_asos/1
  # GET /uni_asos/1.json
  def show
  end

  # GET /uni_asos/new
  def new
    @uni_aso = UniAso.new
  end

  # GET /uni_asos/1/edit
  def edit
  end

  # POST /uni_asos
  # POST /uni_asos.json
  def create
    @uni_aso = UniAso.new(uni_aso_params)

    respond_to do |format|
      if @uni_aso.save
        format.html { redirect_to @uni_aso, notice: 'Uni aso was successfully created.' }
        format.json { render :show, status: :created, location: @uni_aso }
      else
        format.html { render :new }
        format.json { render json: @uni_aso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uni_asos/1
  # PATCH/PUT /uni_asos/1.json
  def update
    respond_to do |format|
      if @uni_aso.update(uni_aso_params)
        format.html { redirect_to @uni_aso, notice: 'Uni aso was successfully updated.' }
        format.json { render :show, status: :ok, location: @uni_aso }
      else
        format.html { render :edit }
        format.json { render json: @uni_aso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uni_asos/1
  # DELETE /uni_asos/1.json
  def destroy
    @uni_aso.destroy
    respond_to do |format|
      format.html { redirect_to uni_asos_url, notice: 'Uni aso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uni_aso
      @uni_aso = UniAso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uni_aso_params
      params.require(:uni_aso).permit(:Union, :Campo)
    end
end

app/helpers/uni_asos_helper.rb
module UniAsosHelper
end

app/views/uni_asos/_form.html.erb
<div>
    <div class="col-md-6 center-block no-float form-login padding_top">
      <%= form_for(@uni_aso) do |f| %>
  <% if @uni_aso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uni_aso.errors.count, "error") %> prohibited this uni_aso from being saved:</h2>

      <ul>
      <% @uni_aso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Union %><br>
    <%= f.text_field :Union %>
  </div>
  <div class="field">
    <%= f.label :Campo %><br>
    <%= f.text_field :Campo %>
  </div>
  <div class="actions">
    <center>
      <a><%= link_to '.', :back, :class=>" fa fa-arrow-circle-o-left fa-2x btn btn-border-info btn-rounded btn-lg" %></a>
      <a><%= f.submit "Ingresar Datos", :class=>"btn btn-border-info btn-rounded btn-lg" %></a>
    </center>
  </div>
<% end %>
</div>
</div>


<!--%= f.collection_select(:office_id, Office.all, :id, :nombre_nit_sucursal, :include_blank => "Por favor seleccione...") %>
-->
<script>
  $(document).ready(function () {
            $('select').material_select();
        });
</script>

app/views/uni_asos/edit.html.erb
<font face="comic sans ms"><h1 class="text-info">Editar Union/Campo</h1></font>

<%= render 'form' %>

app/views/uni_asos/index.html.erb
<font face="comic sans ms"><h1 class="text-info">Campos</h1></font>

<div class="col-md-10 center-block no-float form-login padding_top">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Union</th>
      <th>Campo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uni_asos.each do |uni_aso| %>
      <tr>
        <td><%= uni_aso.Union %></td>
        <td><%= uni_aso.Campo %></td>
        <td><%= link_to '', uni_aso, :class=>"fa fa-eye fa-1x" %></td>
        <td><%= link_to '', edit_uni_aso_path(uni_aso), :class=>"fa fa-pencil fa-1x" %></td>
        <td><%= link_to '', uni_aso, :class=>"fa fa-trash-o fa-1x", method: :delete, data: { confirm: '¿Esta Seguro que desea Eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<div class="actions">
  <a><%= link_to 'Nuevo Campo', new_uni_aso_path, :class=>" fa fa-plus-circle fa-2x btn btn-border-info btn-rounded btn-lg" %></a>
</div>

app/views/uni_asos/new.html.erb
<font face="comic sans ms"><h1 class="text-info">Nuevo Union/Campo</h1></font>

<%= render 'form' %>

app/views/uni_asos/show.html.erb
<div class="col-md-10 center-block no-float form-login padding_top">

<div class="panel panel-info">
  <div class="panel-heading"><center>Uniones y Campos</center></div>
  
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Union:</div>
      <div class="col-md-8"><%= @uni_aso.Union %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Campo:</div>
      <div class="col-md-8"><%= @uni_aso.Campo %></div>
    </div>
  </div>
</div>

<div class="actions">
  <a><%= link_to 'Back', uni_asos_path, :class=>" fa fa-arrow-circle-o-left fa-2x btn btn-border-info btn-rounded btn-lg" %></a>
</div>

</div>