config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
  get 'colegios/micolegio'
  resources :docentes
  resources :colegios
  resources :uni_asos
  
  devise_for :usuarios, controllers: {registrations: "registrations"}
  devise_scope :usuario do
    authenticated :usuario do
      root 'welcome#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :usuarios
end

app/models/colegio.rb
class Colegio < ActiveRecord::Base
    has_many :docentes
    has_attached_file :logo, styles: { croppable: "491x343", medium: "1280x720" }
    validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/
    before_save :default_values
    cattr_accessor :current_usuario
    
    
    
    def default_values
        self.creado_by ||= Colegio.current_usuario.usuario
    end
end

app/controllers/colegios_controller.rb
class ColegiosController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_colegio, only: [:show, :edit, :update, :destroy, :listadocente]

  # GET /colegios
  # GET /colegios.json
  def index
    if current_usuario.rol == "Administrador"
      @colegios = Colegio.all
    end
  end
  
  def micolegio
    if current_usuario.rol == "Administrador Colegio"
      @colegios = Colegio.where("nombre = ?", current_usuario.nombre)
    end
  end
  
  # GET /colegios/1
  # GET /colegios/1.json
  def show
    @listadocente = Docente.where("colegio_id = ?", set_colegio.nombre)
  end

  # GET /colegios/new
  def new
    @colegio = Colegio.new
  end

  # GET /colegios/1/edit
  def edit
  end

  # POST /colegios
  # POST /colegios.json
  def create
    @colegio = Colegio.new(colegio_params)

    respond_to do |format|
      if @colegio.save
        format.html { redirect_to @colegio, notice: 'Colegio was successfully created.' }
        format.json { render :show, status: :created, location: @colegio }
      else
        format.html { render :new }
        format.json { render json: @colegio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colegios/1
  # PATCH/PUT /colegios/1.json
  def update
    respond_to do |format|
      if @colegio.update(colegio_params)
        format.html { redirect_to @colegio, notice: 'Colegio was successfully updated.' }
        format.json { render :show, status: :ok, location: @colegio }
      else
        format.html { render :edit }
        format.json { render json: @colegio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colegios/1
  # DELETE /colegios/1.json
  def destroy
    @colegio.destroy
    respond_to do |format|
      format.html { redirect_to colegios_url, notice: 'Colegio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colegio
      @colegio = Colegio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def colegio_params
      params.require(:colegio).permit(:nombre, :direccion, :telefono, :url, :logo, :cursoMin, :cursoMax, :modalidad, :ubicacion, :campoLocal, :union, :pais)
    end
end

app/helpers/colegios_helper.rb
module ColegiosHelper
end

app/views/colegios/_form.html.erb
<div>
    <div class="col-md-6 center-block no-float form-login padding_top">
      <%= form_for(@colegio) do |f| %>
  <% if @colegio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@colegio.errors.count, "error") %> prohibited this colegio from being saved:</h2>

      <ul>
      <% @colegio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, :value=> current_usuario.nombre %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <h1 class="text-danger btn btn-border-info"><%= f.file_field :logo %></h1>
  </div>
  <div class="field">
    <%= f.label :cursoMin %><br>
    <%= f.text_field :cursoMin %>
  </div>
  <div class="field">
    <%= f.label :cursoMax %><br>
    <%= f.text_field :cursoMax %>
  </div>
  <div class="field">
    <%= f.label :modalidad %><br>
    <%= f.text_field :modalidad %>
  </div>
  <div class="field">
    <%= f.label :ubicacion %><br>
    <%= f.text_field :ubicacion %>
  </div>
  <div class="field">
    <%= f.label :union %><br>
    <h1 class="text-danger"><%= f.select :union, ['Norte', 'Sur'], :include_blank => "Por favor seleccione..." %></h1>
  </div>
  
  <div class="field">
    <%= f.label :campoLocal %><br>
    <h1 class="text-danger"><%= f.collection_select(:campoLocal, UniAso.all, :Campo, :Campo, :include_blank => "Por favor seleccione...") %></h1>
  </div>
  <div class="field">
    <%= f.label :pais %><br>
    <%= f.text_field :pais %>
  </div>
  <div class="actions">
    <center>
      <a><%= link_to '.', :back, :class=>" fa fa-arrow-circle-o-left fa-2x btn btn-border-info btn-rounded btn-lg" %></a>
      <a><%= f.submit "Ingresar Datos Colegio", :class=>"btn btn-border-info btn-rounded btn-lg" %></a>
    </center>
  </div>
<% end %>
</div>
</div>

<script>
  $(document).ready(function () {
            $('select').material_select();
        });
</script>

app/views/colegios/edit.html.erb
<font face="comic sans ms"><h1 class="text-info">Editar Colegio</h1></font>

<%= render 'form' %>

app/views/colegios/index.html.erb
<font face="comic sans ms"><h1 class="text-info">Colegios</h1></font>

<div class="col-md-10 center-block no-float form-login padding_top">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th>Modalidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colegios.each do |colegio| %>
      <tr>
        <td><%= colegio.nombre %></td>
        <td><%= colegio.direccion %></td>
        <td><%= colegio.telefono %></td>
        <td><%= colegio.modalidad %></td>
        <td><%= link_to '', colegio, :class=>"fa fa-eye fa-1x" %></td>
        <td><%= link_to '', edit_colegio_path(colegio), :class=>"fa fa-pencil fa-1x" %></td>
        <td><%= link_to '', colegio, :class=>"fa fa-trash-o fa-1x", method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<div class="actions">
  <a><%= link_to 'Colegio', new_colegio_path, :class=>" fa fa-plus-circle fa-2x btn btn-border-info btn-rounded btn-lg" %></a>
</div>

app/views/colegios/micolegio.html.erb
<div class="col-md-10 center-block no-float">
    <div>
        <br>
    <font face="comic sans ms"><h1 class="text-info text-center"><%= current_usuario.nombre %></h1></font>
    </div>
    <div class="text-center">

        <% i = 0 %>
        <% @colegios.each do |colegio| %>
            <% if colegio.nombre == current_usuario.nombre %>
            <div class="col-md-5">
                <div class="card-group">
                    <div class="card">
                    <img class="img-fluid" src="<%= colegio.logo.url(:croppable) %>" alt="Card image cap">
                        <div class="card-block">
                            <font face="Times New Roman"><h4 class="card-title text-info"><%= colegio.nombre %></h4></font>
                            <p class="card-text">
                                <b>Telefono:</b> <%= colegio.telefono %><br>
                                <b>Campo Local:</b> <%= colegio.campoLocal %><br>
                                <b>Union:</b> <%= colegio.union %><br>
                                <b>Pais:</b> <%= colegio.pais %><br> 
                                <%= link_to '  Editar', edit_colegio_path(colegio), :class=> "fa fa-pencil btn btn-border-info" %> |
                                <%= link_to '  Ver', colegio, :class=> "fa fa-eye btn btn-border-info" %><br>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-5 col-md-offset-2">
                <div class="card-group">
                    <div class="card">
                        <img class="img-fluid" src="http://icon-icons.com/icons2/343/PNG/512/Teachers_35749.png" alt="Card image cap">
                        <div class="card-block">
                            <center><font face="Times New Roman"><h4 class="card-title text-info">Empleados</h4></font></center>
                            <%= link_to '  Nuevo', new_docente_path(@user), :class=> "fa fa-pencil btn btn-border-info" %> | 
                            <%= link_to '  Ver', docentes_path(@user), :class=> "fa fa-eye btn btn-border-info" %><br>
                        </div>
                    </div>
                </div>
            </div>
            <% i = 1 %>
            <% end %>
        <% end %>    
            <% if i == 0 %>
            <div class="col-md-5">
                <div class="card-group">
                    <div class="card">
                        <div class="card-block">
                            <font face="Times New Roman"><h4 class="card-title text-info">Ingrese los Datos de su Colegio</h4></font>
                            <p class="card-text">
                                <%= link_to ' Datos Colegio', new_colegio_path, :class=> "fa fa-plus-circle btn btn-border-info" %>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-5 col-md-offset-2">
                <div class="card-group">
                    <div class="card">
                        <img class="img-fluid" src="http://icon-icons.com/icons2/343/PNG/512/Teachers_35749.png" alt="Card image cap">
                        <div class="card-block">
                            <center><font face="Times New Roman"><h4 class="card-title text-info">Sin Colegio Para Empleados</h4></font></center>
                            
                        </div>
                    </div>
                </div>
            </div>
            <%end%>
        
    </div>

</div>

app/views/colegios/new.html.erb
<font face="comic sans ms"><h1 class="text-info">Nuevo Colegio</h1></font>
<%= render 'form' %>

app/views/colegios/show.html.erb
<div class="col-md-10 center-block no-float form-login padding_top">

<div class="panel panel-info">
  <div class="panel-heading"><center><%= @colegio.nombre %></center></div>
  <div class="panel-body">
    <div class="row">
      <div class="text-center">
          <header class="background-cover" style="background:url(<%= @colegio.logo.url(:medium) %>);top:0px;left:0px;width:100%;height:400px;background-size: cover;">
          </header>
      </div>
    </div>
  </div>
  
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Direccion:</div>
      <div class="col-md-8"><%= @colegio.direccion %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Telefono:</div>
      <div class="col-md-8"><%= @colegio.telefono %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Url:</div>
      <div class="col-md-8"><%= link_to @colegio.url, @colegio.url, :target => '_blank' %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Curso Minimo:</div>
      <div class="col-md-8"><%= @colegio.cursoMin %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Curso Maximo:</div>
      <div class="col-md-8"><%= @colegio.cursoMax %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Modalidad:</div>
      <div class="col-md-8"><%= @colegio.modalidad %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Ubicacion:</div>
      <div class="col-md-8"><%= @colegio.ubicacion %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Campo Local:</div>
      <div class="col-md-8"><%= @colegio.campoLocal %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Union:</div>
      <div class="col-md-8"><%= @colegio.union %></div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">Pais:</div>
      <div class="col-md-8"><%= @colegio.pais %></div>
    </div>
  </div>
</div>

<div class="actions">
  <a><%= link_to '  Back', :back, :class=>" fa fa-arrow-circle-o-left fa-2x btn btn-border-info btn-rounded btn-lg" %></a>
  <a><%= link_to '  Home', welcome_index_path, :class=>" fa fa-home fa-2x btn btn-border-info btn-rounded btn-lg" %></a>
  <button class="fa fa-list fa-2x btn btn-border-info btn-rounded btn-lg" data-toggle="modal" data-target=".bd-example-modal-lg">Listar Docentes</button>
</div>

</div>


  <!-- Large modal -->


<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

        <font face="comic sans ms"><h1 class="text-info">Empleados</h1></font>
        
        <div class="col-md-10 center-block no-float form-login padding_top">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Apellido</th>
              <th>Telefono</th>
              <th>Cargo</th>
              <th>Colegio</th>
              <th colspan="3"></th>
            </tr>
          </thead>
        
          <tbody>
            <% @listadocente.each do |docente| %>
              <tr>
                <td><%= docente.nombre %></td>
                <td><%= docente.apellido %></td>
                <td><%= docente.telefono %></td>
                <td><%= docente.cargo %></td>
                <td><%= docente.colegio_id %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        </div>
        <br>
      
    </div>
  </div>
</div>